spring.application.name=feeder-server

# MQTT configuration (disabled by default)
mqtt.enabled=false
mqtt.broker=tcp://localhost:1883
mqtt.clientId=feeder-server
mqtt.username=alex
mqtt.password=123
mqtt.defaultTopic=feeder/updates
