spring.application.name=feeder-server

# Server configuration
server.servlet.context-path=/feeder-service/api

# MQTT configuration (disabled by default)
mqtt.enabled=false
mqtt.broker=tcp://localhost:1883
mqtt.clientId=feeder-server
mqtt.username=alex
mqtt.password=123
mqtt.defaultTopic=feeder/updates

# PostgreSQL datasource (local dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/feeder
spring.datasource.username=alex
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
